---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Restart repmgrd
  ansible.builtin.systemd:
    name: repmgrd
    state: restarted
  become: true

- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
  become: true
